// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	goods "coupon-platform/taobao-api/internal/handler/goods"
	"coupon-platform/taobao-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/home",
				Handler: goods.HomeListHandler(serverCtx),
			},
		},
	)
}
