// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Email     string `json:"email"`
	Telephone string `json:"telepohone"`
	Username  string `json:"user_name"`
}

type RegisterResp struct {
	Uid   int64  `json:"uid"`
	Email string `json:"email"`
}

type LoginReq struct {
	Telephone string `json:"telephone"`
	Password  string `json:"password"`
}

type LoginResp struct {
	Uid      int64  `json:"uid"`
	Username string `json:"user_name"`
	Headpic  string `json:"head_pic"`
	Email    string `json:"email"`
	Token    string `json:"token"`
}

type UserReq struct {
	Uid       int64  `json:"uid"`
	Telephone string `json:"telephone,optional"`
}

type UserResp struct {
	Uid      int64  `json:"uid"`
	Username string `json:"user_name"`
	Headpic  string `json:"head_pic"`
}
