// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type PageList struct {
	Pg       int `json:"pg"`
	PageSize int `json:"page_size"`
}

type OrderListReq struct {
	Pg        int64  `json:"pg"`
	PageSize  int64  `json:"page_size"`
	Uid       int64  `json:"uid,optional"`
	OrderSn   string `json:"order_sn,optional"`
	StartTime int64  `json:"start_time,optional"`
	EndTime   int64  `json:"end_time,optional"`
}

type OrderList struct {
	Uid        int64  `json:"uid"`
	OrderSn    string `json:"order_sn"`
	TradeNo    string `json:"trade_no"`
	IsActive   int64  `json:"is_active"`
	CreateTime int64  `json:"create_time"`
}

type OrderListResult struct {
	PageList
	List []*OrderListResult `json:"list"`
}

type OrderListResp struct {
	Response
	Result OrderListResult `json:"result"`
}

type OrderInfoReq struct {
	Uid     int64  `json:"uid,optional"`
	OrderSn string `json:"order_sn,optional"`
}

type OrderInfoResp struct {
	Uid        int64  `json:"uid"`
	UserName   string `json:"user_name"`
	Telephone  string `json:"telephone"`
	OrderSn    string `json:"order_sn"`
	TradeNo    string `json:"trade_no"`
	IsActive   int64  `json:"is_active"`
	CreateTime int64  `json:"create_time"`
}
