// Code generated by goctl. DO NOT EDIT.
package types

type UserReq struct {
	Uid       int64  `json:"uid"`
	Telephone string `json:"Telephone,optional"`
}

type UserResp struct {
	Uid      int64  `json:"uid"`
	Username string `json:"user_name"`
}
