// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type PageList struct {
	Pg       int `json:"pg"`
	PageSize int `json:"page_size"`
}

type GoodsReq struct {
	Pg       int64 `json:"pg"`
	PageSize int64 `json:"page_szie"`
}

type GoodsResp struct {
	Response
	Result GoodsRespResult `json:"result"`
}

type GoodsRespResult struct {
	Tid        int64  `json:"tid"`
	ShopTitle  string `json:"shop_name"`
	GoodsTitle string `json:"goods_title"`
}
