// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	order "coupon-platform/order-center/api-service/internal/handler/order"
	"coupon-platform/order-center/api-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/list",
				Handler: order.OrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/info",
				Handler: order.OrderInfoHandler(serverCtx),
			},
		},
	)
}
